default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("PGHOST") { "localhost" } %>
  port: <%= ENV.fetch("PGPORT") { 5432 } %>
  username: <%= ENV.fetch("PGUSER") { "postgres" } %>
  password: <%= ENV["PGPASSWORD"] %>

development:
  <<: *default
  database: uptime_development

test:
  <<: *default
  database: uptime_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
